# Generated by Django 3.1.7 on 2021-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='unit',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
